import random

# Przekleństwa dla każdego (ogólne dla Imperium)
przeklenstwa_ogolne = [
    "Ty parszywy mutantowy pomiocie, nawet Nurgle by się tobą brzydził!",
    "Twoja matka to skaven, a ojciec pewnie był pijanym niziołkiem na targu!",
    "Na Sigmara i jego jebane młoty, będziesz żałował tej arogancji, dzieciaku!",
    "Nawet goblińska armia byłaby w stanie zorganizować się lepiej niż twoje życie!",
    "Na Zęby Taala! Kiedy ta burza w końcu przestanie, jebany skurwysynie?!",
    "Masz mózg jak nadzienie do ciasta z Kislevu i ryj jak trumna z Ostermarku!",
    "Jest tak cicho, że słyszałbyś, jak Shallya puszcza bąka, skurwysynu!",
    "Czy twój mózg jest zawsze tak wolny jak barka na Reiku, płacona na dzień?",
    "Na gorącym moczu Ulrica, jego piekących dupach i wiotkich cyckach! Coś tu śmierdzi, czuję to w powietrzu.",
    "Wartość twoja to mniej niż obietnica Tileańczyka i przysięga Estalijczyka razem wzięte – tylko gówna warte!",
    "Niech Morr weźmie was wszystkich, jebani debile! (Wypierdalać!)",
    "Na brodę Sigmara, jakbym miał tyle wstydu co ty, to bym się zapadł pod ziemię jak gówno w deszczu!",
    "Wyglądasz jakbyś przegrał wszystkie zakłady z Talabeciem i wciąż nie ogarniał, że jesteś totalnym zjebem!",
    "Na Ulrica, twoja twarz wygląda jak jedno wielkie gówno z przesmażonymi oczami!",
    "Twoje życie to bardziej burdel w Karak, niż sprawiedliwość w Imperium.",
    "Masz mózg mniejszy niż gówno wyrzucone z karawany goblinów! Nawet twoje pomysły jebią na kilometr!",
    "Jest tak cicho, że słychać jak Shallya wyciska z siebie najgorsze bąki w historii tej jebanej ziemi!",
    "Ale wyglądasz jak jebane gówno! Nawet złamany kurczak z Reiklandu wyglądałby od ciebie lepiej na polu bitwy!",

    "Ty niedomyty kuflożłopie, nawet gobliny mają więcej honoru!",
    "Ty zapuszczony kurwiu, nawet te jebane skaveny by cię nie chciały w swojej drużynie!",
    "Na brodę Grungniego, jego młot i synów, dzisiaj wieczorem napijemy się na chwałę!",
    "Twoja broda wygląda jak stary mop po napaści skavenów!",
    "Jestem bardziej krasnoludem niż ty i mam wyjebane, wiesz o tym?",
    "Sigmar cię porzucił, Grimnir zapomniał, Valaya się tobą brzydzi, a ja mam cię głęboko w dupie!",
    "Jesteś tak wolny, że nawet elf bez nóg by cię wyprzedził!",
    "Twoje ręce są tak obleśne, że gdybyś dotknął młota, to on by się ze wstydu złamał!",
    "Wolę pić piwo z dziury w ziemi, niż z twojego kufla, bo przynajmniej nie czuję się jakby mnie ktoś jebanym gównem częstował!",
    "Będziesz zapamiętany tylko dlatego, że byłeś najbardziej żałosnym z krasnoludów, który nie potrafił unieść swojego młota!",
    "Grungni musiałby cię za ucho ciągnąć jak karłowatą dziwkę na końcu świata żebyś w końcu ruszył to grube dupsko!",
    "Ty nędzny kąpielowy oszuście, twoja broda to zapuszczona chujnia, która wolałaby umierać w czarnej rynsztoku, niż być widzianą na Karak Azgorod!",
    "Z twoimi umiejętnościami w wojnie to wolałbym dać młot w ręce goblina – przynajmniej by mu się udało w coś trafić!",
    "Jesteś gorszy niż ork w nowych butach – przynajmniej one umieją się ruszać, a ty tylko stoisz tam, brudny jak gówno!",
    "Twoje życie to bardziej karma dla trolla niż prawdziwa chwała dla krasnoluda – zrób coś, żebyś chociaż się nie wstydził samego siebie!",
    "Na Grungniego, twój młot jest bardziej bezużyteczny niż broda skavena na stole do naprawy!",
    "Ty brudny kurwiszonie, twoja broda to strach przed kobiecym ciałem, wolałbym byś nigdy nie wyszedł z czeluści pod ziemią!",
    "Nie potrafisz zrobić nic poza piciem, a i w tym jesteś chujowy.",
    "Na Grungniego, twój młot jest bardziej bezużyteczny niż orkowe gówno w beczce piwa!",
    "Ty jebany pedancie. Twoje ręce są bardziej gładkie niż dupa skavenów,",
    "Będziesz zapamiętany tylko jako ten jebany frajer, który przez całe życie nie nauczył się pić jak krasnolud, tylko jak pieprzony niziołek!",
    "Twoja broda nie jest godna by nazwać ją brodą, to raczej brudny kawałek szczeciny przyklejony do twojej twarzy!",
    "Jebany buraku, z twoimi umiejętnościami w walce to mógłbyś walczyć tylko z ogórkami, i to takimi, które są zgniłe!",
    "Twój honor jest tak czysty jak cuchnący jebany gównojad w Karak Azgorod! Wstydź się oddychać w tym jebanym życiu!",
    "Nawet sam Grungni by poprosił, żebyś spierdalał, tylko hańbę i zgubę przyniesiesz na nas.",
    "Ty zapuszczony kurwiu, wyglądasz jakbyś miał brodę z gówna i wstydziłbyś się w ogóle wychylić łeb z gór! ",
    "Na młot Grimnira, twoja broda jest bardziej parszywa niż gnijący skaven we wszystkich jaskiniach pod Karak Azgorod!",
    "Wiesz, co jest bardziej przydatne niż twoje ręce? Jeden z tych jebanych goblińskich zardzewiałych noży, przynajmniej by coś trafiły! ",
    "Ty brudny, pociągający za sobą wstydzie, z tą brodą jak zgnity koralik, wolałbym cię widzieć jako goblińską zapaszkę niż żywego krasnoluda!",
    "Na Zęby Grungniego, bez ciebie każda bitwa byłaby spokojniejsza, bo przynajmniej nikt by nie widział jak śmierdzisz jak pierdolone gówno pod ziemią!",
    "Jebany pustaku, będziesz zapamiętany tylko dlatego, że miałeś brodę pełną smrodu i wstydziłeś się pić piwo jak prawdziwy krasnolud, tylko jak jebany niziołek!",
    "Ty idiotyczny, zapuszczony debilu, na pewno zgubiłbyś młot szybciej, niż gobliny zgubiłyby swoją brudną mapę!",
    "Czuję, że w każdej walce tylko opóźniasz nasz marsz – idź w pizdu, niech cię pożrą gobliny z zachowaniem honoru niż taki przygłup jak ty!",
    "Niech ci młot Grungniego pierdolnie w pysk! Jesteś bardziej bezużyteczny niż orkowy chrzest pożegnalny!",
    "Na brodę moją, ty za przeproszeniem śmierdzący pieprzony trollu! Nawet gobliny zaczynają się śmiać, gdy widzą, jak trzymasz młot!",
    "Niech cię Grungni pieprzy! Jesteś tak dobry w walce, jak orkowy młot w rękach goblina – gówna wart!",
    "Żeby ci broda wypadła, a twoje pieprzone ręce zamieniły się w goblińskie łapy, których nikt nie chce w swojej drużynie!",
    "Sigmar by cię ukarał, ale nawet on nie ma cierpliwości na śmierdzącego idiotę z gór, który zapomniał, jak wygląda prawdziwa bitwa!",
    "Twoja broda wygląda jakby ją pieprzony goblin wytarł w swoje zardzewiałe buty, a potem zapomniał, że istnieje woda!",
    "Twoje życie to jak goblińska kopalnia – pełno błota, ciemności i pierdolonego gówna, z którego nigdy nie wyjdziesz!",
    "Jebany pasożycie! Nawet najgorszy niziołek z Reiklandu nie popełniłby takich głupot jak ty, ty brudny plebsie!",
    "Jesteś jak zardzewiały pieprzony gwóźdź, który nic nie trzyma – za to śmierdzi jak pół kilograma gnijących skavenów w komorze!",
    "Niech cię pieprzy ten cały Sigmar, jesteś bardziej żałosny niż ork w szpilkach! Niezdolny do niczego prócz picia z ujebanego w gównie kufla!",
    "Ty pierdolony bełkocie, jak się na ciebie patrzy, czuję, że z każdym oddechem tracę cząstkę swojej dumy – kim ty jesteś, żeś się urodził, gówniany lądzie?!",
    "Poczekaj, aż cię jebnę młotem, może wtedy zrozumiesz, że nie masz prawa tutaj siedzieć, ty jebany zardzewiały karłówku!",
    "Twoja twarz jest bardziej wypalona niż najgorsza kuchnia w Karak – tylko się zastanawiam, co mnie zabiło najpierw: widok ciebie czy ten odór!",
    "Coś ci się pomieszało, ty śmierdząca, zbutwiała szmato! Nawet najgorszy goblin miałby więcej rozumu niż ty!",
    "Ty obsrany karczemny psie, wyglądasz jak wódz grupy goblinów, który po każdej wódce zrywa się na nogi, tylko po to, żeby się rozbić o najbliższy stół!",
    "Jestem bardziej krasnoludem niż ty, ty bezczelny, szeleszczący zgnilu, bezmyślny kawałku zapuszczonego chrząstka!",
    "Twój nos ma tyle grzechów na sumieniu, że nawet kobieta z Reiklandu nie powinna go tknąć, bo zgnije przed porannym słońcem, ty jebiącym szczynami potworze!",
    "I niech cię pieprzy cały Kislev, a jeśli masz zamiar zginąć w tej walce, to chociaż zabierz ze sobą ten zapach, co go zostawiasz za sobą, bo nie wytrzymam, jebany łachmyto!",
    "Wolałbym tańczyć nago na stole z goblinem niż jeszcze raz słuchać, jak się odzywasz, pieprzony wraku, którego matka wysrała na świat razem z gnojówką",
]


def losuj_przeklenstwo():
    return random.choice(przeklenstwa_ogolne)
