from .dm import dm_command
from .sesja import sesja_command
from .purge import purge_command
from .hello import hello_command
from .ochlapus import ochlapus_command
from .roll import roll_command
from .umiejki import umiejki_command
from .zdolnosci import zdolnosci_command
from .klnij import klnij_command
from .help import help_command
from .wydarzenia import wydarzenia_command
from .notatki import wydarzenia_command
from .npc import wydarzenia_command
